### ISSUE TITLE
cannot find package "github.com/869413421/wechatbot/bootstrap" in any of:

### ISSUE THREAD

**Issue by 2953225996** [869413421/wechatbot#12]
![QQ截图20221208123635](https://user-images.githubusercontent.com/99384711/206357903-335aee13-3188-4429-a45f-6a69bfce1baa.png)

**Comment by 869413421** [comment]
> ![QQ截图20221208123635](https://user-images.githubusercontent.com/99384711/206357903-335aee13-3188-4429-a45f-6a69bfce1baa.png)
> 

开启go module
