### ISSUE TITLE
间歇性的停止回答，不是网络的问题

### ISSUE THREAD

**Issue by f1ndm1** [869413421/wechatbot#13]
提问后，部分问题（常规）提出来后，无结果返回，且当前问题被阻塞的情况下，无法提问下一个问题

**Comment by yn668** [comment]
我也发现了，动不动就卡死了

**Comment by 869413421** [comment]
> 提问后，部分问题（常规）提出来后，无结果返回，且当前问题被阻塞的情况下，无法提问下一个问题

提供下日志信息，有可能是GTP一直不响应

**Comment by f1ndm1** [comment]
应该是GTP响应的问题，需要很长一段时间才能返回结果，然后再接着执行下一项。

**Comment by f1ndm1** [comment]
11
