### ISSUE TITLE
linux pm2部署报错

### ISSUE THREAD

**Issue by zhiyanzhaijie** [869413421/wechatbot#18]
当使用pm2部署本项目时，会报错。如果使用nohup工具就不会出现问题

**Comment by 869413421** [comment]
> ![image](https://user-images.githubusercontent.com/96094521/206626490-7debfc97-b5d3-4c9a-932d-0e7045ee53c3.png)
> 

建议使用编译好使用二进制运行。

**Comment by zhiyanzhaijie** [comment]
> 

原来如此，main.go还要编译后才能PM2跑

**Comment by 869413421** [comment]
> > 
> 
> 原来如此，main.go还要编译后才能PM2跑
> 

如果问题解决请关闭。
