### ISSUE TITLE
使用docker部署后，查看二维码无内容

### ISSUE THREAD

**Issue by shen1in** [869413421/wechatbot#21]
![图片](https://user-images.githubusercontent.com/68018113/206611524-fee3c79f-29cb-4c76-978b-830ec5077c80.png)

**Comment by 869413421** [comment]
> ![图片](https://user-images.githubusercontent.com/68018113/206611524-fee3c79f-29cb-4c76-978b-830ec5077c80.png)
> 

进入容器检查进程是否在运行，进程名称为项目名称。
