### ISSUE TITLE
Linux部署之后运行会报错

### ISSUE THREAD

**Issue by lmuiotctf** [869413421/wechatbot#25]
![ee3846d241b194a1d6de34b8f572af6](https://user-images.githubusercontent.com/52068443/206656090-b750a605-2590-422c-8dc2-ab00008e6974.png)

**Comment by nagaame** [comment]
you should use ` go mod tidy` command in project directory install dependencies before `go run main.go `

**Comment by Jsharkc** [comment]
看起来像 golang 版本问题

**Comment by 869413421** [comment]
> ![image](https://user-images.githubusercontent.com/52068443/206685588-2aa43964-d53e-45fc-8bc1-b8da42859828.png)
> this error

需要更新你的go版本，使用用1.6以上版本
