### ISSUE TITLE
linux上报错gtp api status code not equals 200

### ISSUE THREAD

**Issue by WMMMD** [869413421/wechatbot#28]
网络环境是US服务器、Key核实正常

**Comment by lslswin** [comment]
gtp request error: gtp api status code not equals 200,code is 401 同样的问题

**Comment by lmuiotctf** [comment]
gtp request error: gtp api status code not equals 200,code is 429

**Comment by 869413421** [comment]
更新到最新版本代码，日志中有请求接口错误的具体信息。

**Comment by Cupcc** [comment]
> 

使用docker运行也是这个错误。

**Comment by 869413421** [comment]
> > 
> 
> 使用docker运行也是这个错误。

看上面的回复

**Comment by 869413421** [comment]
看最新readme
