### ISSUE TITLE
好像是上下文的问题，他老是在补充我的话

### ISSUE THREAD

**Issue by ZakiuC** [869413421/wechatbot#29]
比如我问了一个问题，没打问号，他就回了我一个问号，或者我说了一半的话就类似短语，他会给我补充上去。而不是和我对话，不知道具体是哪出了问题

**Comment by lalalabox** [comment]
这个正常吧。它第一步其实是**预处理**你的问题，如果你的问题在它看来缺少了一部分，它会**自动补全**。
之后，使用这个处理过的问题作为**真正的输入**。

**Comment by 869413421** [comment]
> 这个正常吧。它第一步其实是**预处理**你的问题，如果你的问题在它看来缺少了一部分，它会**自动补全**。
> 之后，使用这个处理过的问题作为**真正的输入**。

正解。
