### ISSUE TITLE
好像不如ChatGPT智能

### ISSUE THREAD

**Issue by Loummer** [869413421/wechatbot#3]
我测试了一下，回答的问题有点傻瓜。

可以直接通过获取ChatGPT cookie的方式对接上ChatGPT吗？

**Comment by lyonxh** [comment]
本来就是个智能搜索引擎

**Comment by 869413421** [comment]
因为没有做上下文联系，直接调用会有差别。

**Comment by 869413421** [comment]
> 我测试了一下，回答的问题有点傻瓜。
> 
> 可以直接通过获取ChatGPT cookie的方式对接上ChatGPT吗？

ck会过期，key不会
