### ISSUE TITLE
登陆时出错，请问如何解决

### ISSUE THREAD

**Issue by eeee0717** [869413421/wechatbot#31]
![image](https://user-images.githubusercontent.com/70054568/206709959-0c622ebe-3185-470d-8046-303b23188f32.png)

**Comment by lalalabox** [comment]
我也遇到了，你试试**退出电脑微信**，然后多尝试几次就可以成功了。

**Comment by eeee0717** [comment]
好的 已经解决，是不是可以添加关键词功能，不然好像会一直回复
