### ISSUE TITLE
聊着聊着上下文字数就超限了

### ISSUE THREAD

**Issue by ljdzxx** [869413421/wechatbot#35]
2022/12/10 04:23:12 {
  "error": {
    "message": "This model's maximum context length is 4097 tokens, however you requested 4101 tokens (3589 in your prompt; 512 for the completion). Please reduce your prompt; or completion length.",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

2022/12/10 04:23:12 gtp request error: gtp api status code not equals 200,code is 400 
2022/12/10 04:23:13 RetCode:0  Selector:2

**Comment by 869413421** [comment]
发送口令:我要问下一个问题，清空上下文

**Comment by ljdzxx** [comment]
但是这样对用户就不友好了，应该修改一下，自动检测字数，超限之后从前面截断超长部分

**Comment by ljdzxx** [comment]
而且在群里@机器人“我要问下一个问题”无效，私聊才有效吧？应该是个BUG

**Comment by 869413421** [comment]
已修复。

**Comment by 869413421** [comment]
> 但是这样对用户就不友好了，应该修改一下，自动检测字数，超限之后从前面截断超长部分

这个问题已经注意到，后续会跟进。

**Comment by yongtaof** [comment]
建议直接清空上下文并告知用户上下文超过，已经清空了，可以问下一个问题，避免后续聊不了了，我暂时本地这样处理了。
