### ISSUE TITLE
有什么办法可以解决模型学习数据库 老旧的问题

### ISSUE THREAD

**Issue by Angelajzr** [869413421/wechatbot#37]
问题：最新全球新冠死亡数据
回答：本消息由 chatGPT Bot回复：
截至2021年1月6日，全球新冠病毒死亡人数超过了2,600,000人，其中美国死亡人数最高，超过了400,000人。
数据还是2021年1月6日

**Comment by Angelajzr** [comment]
有什么办法能让他模型继续学习到最新数据

**Comment by 869413421** [comment]
> 有什么办法能让他模型继续学习到最新数据
> 

没有，除非openai发布新模型
