### ISSUE TITLE
请求GTP出错了

### ISSUE THREAD

**Issue by noovertime7** [869413421/wechatbot#41]
gtp request error: 请求GTP出错了，gtp api status code not equals 200,code is 401 ,details:  {
    "error": {
        "message": "Incorrect API key provided: api key. You can find your API key at https://beta.openai.com.",
        "type": "invalid_request_error",
        "param": null,
        "code": "invalid_api_key"
    }
}

**Comment by 869413421** [comment]
请配置好api key再运行项目
