### ISSUE TITLE
Dockerfile19层

### ISSUE THREAD

**Issue by goodnull** [869413421/wechatbot#43]
Dockerfile 19层，build也是失败的，而且900多M，肯定是不正常的

**Comment by 869413421** [comment]
> Dockerfile 19层，build也是失败的，而且900多M，肯定是不正常的

只有两层，70m，不知道你具体如何编译的，请提供具体信息。

**Comment by 869413421** [comment]
> Dockerfile 19层，build也是失败的，而且900多M，肯定是不正常的

只有两阶段编译，正常只有70m。你如何进行编译，请提供具体信息。

**Comment by 869413421** [comment]
没提供详细信息，提供后再开启。
