### ISSUE TITLE
手机微信退出后，机器人就不能用了

### ISSUE THREAD

**Issue by chengjieYan** [869413421/wechatbot#49]
如题，需要保持手机微信在线吗

**Comment by 869413421** [comment]
> 如题，需要保持手机微信在线吗
> 

你好，需要的。

**Comment by zhang-cuishan** [comment]
> > 如题，需要保持手机微信在线吗
> 
> 你好，需要的。

手机可以切换微信账号吗？

**Comment by evan-xie** [comment]
> > > 如题，需要保持手机微信在线吗
> > 
> > 
> > 你好，需要的。
> 
> 手机可以切换微信账号吗？

不能的 我还特意找了个旧手机用来登录注册的小号
