### ISSUE TITLE
扫描登录成功后, 就直接结束go程序了

### ISSUE THREAD

**Issue by baicaiit** [869413421/wechatbot#5]
```
2022/12/07 18:22:33 扫码成功,请在手机上确认登录
2022/12/07 18:22:44 登录成功
2022/12/07 18:22:44 RetCode:0  Selector:2
2022/12/07 18:22:45 RetCode:0  Selector:2
2022/12/07 18:22:45 hadler Received msg : 
2022/12/07 18:22:48 RetCode:1101  Selector:0
```

**Comment by 869413421** [comment]
> ```
> 2022/12/07 18:22:33 扫码成功,请在手机上确认登录
> 2022/12/07 18:22:44 登录成功
> 2022/12/07 18:22:44 RetCode:0  Selector:2
> 2022/12/07 18:22:45 RetCode:0  Selector:2
> 2022/12/07 18:22:45 hadler Received msg : 
> 2022/12/07 18:22:48 RetCode:1101  Selector:0
> ```

日志显示在正常运行，你是编译后执行还是直接run?

**Comment by 869413421** [comment]
> ```
> 2022/12/07 18:22:33 扫码成功,请在手机上确认登录
> 2022/12/07 18:22:44 登录成功
> 2022/12/07 18:22:44 RetCode:0  Selector:2
> 2022/12/07 18:22:45 RetCode:0  Selector:2
> 2022/12/07 18:22:45 hadler Received msg : 
> 2022/12/07 18:22:48 RetCode:1101  Selector:0
> ```

应该是你其他地方重新登陆微信了

**Comment by 869413421** [comment]
在项目扫码登陆后，会挤掉其他pc端的登陆状态，反之亦然。

**Comment by baicaiit** [comment]
噢噢 了解了
