### ISSUE TITLE
1.1.3版本 过程消息显示不完整

### ISSUE THREAD

**Issue by netcode001** [869413421/wechatbot#54]
使用1.1.3版本 windows对于ChatGPT回复的消息不能显示完整，例如回答写作文，写总结等，只能显示一部分。

**Comment by 869413421** [comment]
> 使用1.1.3版本 windows对于ChatGPT回复的消息不能显示完整，例如回答写作文，写总结等，只能显示一部分。

和你配置的max_tokens长度有关。
