### ISSUE TITLE
用url不显示二维码

### ISSUE THREAD

**Issue by github-plus** [869413421/wechatbot#55]
我是在linux使用docker的，复制url显示的不是二维码，是一串代码"window.QRLogin.code = 200; window.QRLogin.uuid = "wetBdq0DJA==";"
想问下这是怎么回事

**Comment by 869413421** [comment]
> 我是在linux使用docker的，复制url显示的不是二维码，是一串代码"window.QRLogin.code = 200; window.QRLogin.uuid = "wetBdq0DJA==";"
> 想问下这是怎么回事

请直接扫描控制台二维码。
