### ISSUE TITLE
几个小问题，会引起上下文混乱，可以这样修改

### ISSUE THREAD

**Issue by dytxy888** [869413421/wechatbot#58]
获取上下文，拼接在一起时，现在的源码没有对提交的文本进行处理，如果用户打的句子没后没有标点符号，openai会认为话没说完，有时会自作主张补齐，导致答非所问。另外没有在之间加入回车，也容易造成混乱，我作了如下修改，现在运行顺畅多了。

//以下代码对提交的文本预处理
         punct := ",.;!?，。！？、…"
	lastchar := string(requestText[len(requestText)-1:])
	if strings.Index(punct, lastchar) < 0 { //判断最后字符是否加了标点，没有的话加上句号，避免openai自动补齐引起混乱。
		requestText = requestText + "。"
	}
	requestText = "\n" + requestText  //添加一个回车，让AI更更明确哪一个是新信息。

然后再把requestText 和上下文拼接即可，私聊和群聊两边都要这样处理。

**Comment by 869413421** [comment]
> ```
> 获取上下文，拼接在一起时，现在的源码没有对提交的文本进行处理，如果用户打的句子没后没有标点符号，openai会认为话没说完，有时会自作主张补齐，导致答非所问。另外没有在之间加入回车，也容易造成混乱，我作了如下修改，现在运行顺畅多了。
> ```
> 
> //以下代码对提交的文本预处理 punct := ",.;!?，。！？、…" lastchar := string(requestText[len(requestText)-1:]) if strings.Index(punct, lastchar) < 0 { //判断最后字符是否加了标点，没有的话加上句号，避免openai自动补齐引起混乱。 requestText = requestText + "。" } requestText = "\n" + requestText //添加一个回车，让AI更更明确哪一个是新信息。
> 
> 然后再把requestText 和上下文拼接即可，私聊和群聊两边都要这样处理。

还应提交PR

**Comment by 869413421** [comment]
> ```
> 获取上下文，拼接在一起时，现在的源码没有对提交的文本进行处理，如果用户打的句子没后没有标点符号，openai会认为话没说完，有时会自作主张补齐，导致答非所问。另外没有在之间加入回车，也容易造成混乱，我作了如下修改，现在运行顺畅多了。
> ```
> 
> //以下代码对提交的文本预处理 punct := ",.;!?，。！？、…" lastchar := string(requestText[len(requestText)-1:]) if strings.Index(punct, lastchar) < 0 { //判断最后字符是否加了标点，没有的话加上句号，避免openai自动补齐引起混乱。 requestText = requestText + "。" } requestText = "\n" + requestText //添加一个回车，让AI更更明确哪一个是新信息。
> 
> 然后再把requestText 和上下文拼接即可，私聊和群聊两边都要这样处理。

欢迎提交PR

**Comment by 869413421** [comment]
> 

非常好的建议，会抽空处理，感谢你。

**Comment by 869413421** [comment]
> 

你好你提供的代码在中文的时候会产生错误，我已经更正兼容在我的项目中。测试得到积极的效果，再次感谢你提供的方案。

**Comment by 869413421** [comment]
> ```
> 获取上下文，拼接在一起时，现在的源码没有对提交的文本进行处理，如果用户打的句子没后没有标点符号，openai会认为话没说完，有时会自作主张补齐，导致答非所问。另外没有在之间加入回车，也容易造成混乱，我作了如下修改，现在运行顺畅多了。
> ```
> 
> //以下代码对提交的文本预处理 punct := ",.;!?，。！？、…" lastchar := string(requestText[len(requestText)-1:]) if strings.Index(punct, lastchar) < 0 { //判断最后字符是否加了标点，没有的话加上句号，避免openai自动补齐引起混乱。 requestText = requestText + "。" } requestText = "\n" + requestText //添加一个回车，让AI更更明确哪一个是新信息。
> 
> 然后再把requestText 和上下文拼接即可，私聊和群聊两边都要这样处理。

你好你提供的代码在中文的时候会产生错误，我已经更正兼容在我的项目中。测试得到积极的效果，再次感谢你提供的方案。

**Comment by 869413421** [comment]
> > ```
> > 获取上下文，拼接在一起时，现在的源码没有对提交的文本进行处理，如果用户打的句子没后没有标点符号，openai会认为话没说完，有时会自作主张补齐，导致答非所问。另外没有在之间加入回车，也容易造成混乱，我作了如下修改，现在运行顺畅多了。
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > //以下代码对提交的文本预处理 punct := ",.;!?，。！？、…" lastchar := string(requestText[len(requestText)-1:]) if strings.Index(punct, lastchar) < 0 { //判断最后字符是否加了标点，没有的话加上句号，避免openai自动补齐引起混乱。 requestText = requestText + "。" } requestText = "\n" + requestText //添加一个回车，让AI更更明确哪一个是新信息。
> > 然后再把requestText 和上下文拼接即可，私聊和群聊两边都要这样处理。
> 
> 你好你提供的代码在中文的时候会产生错误，我已经更正兼容在我的项目中。测试得到积极的效果，再次感谢你提供的方案。

将追加。号换成追加？号，效果更好。
