### ISSUE TITLE
1.1.3.1阿里云主机 win10下 程序被安全中心隔离

### ISSUE THREAD

**Issue by netcode001** [869413421/wechatbot#59]
![image](https://user-images.githubusercontent.com/20432682/206990045-b2ce524b-d6bc-4e01-9b8d-ba760f4bf2c8.png)

**Comment by netcode001** [comment]
更正操作系统是server 2022 安全中心设置后，可正常work，但是3.1.1没有出现此问题。

**Comment by 869413421** [comment]
> 更正操作系统是server 2022 安全中心设置后，可正常work，但是3.1.1没有出现此问题。

服务器主机的安全策略，自行开放白名单。
