### ISSUE TITLE
为什么没有官网智能啊？

### ISSUE THREAD

**Issue by putianhui** [869413421/wechatbot#6]
我在官网`https://chat.openai.com/chat`里面输入一段话得到的回复和程序回复到微信的不一样。

官网输入回复的更智能？

**Comment by 869413421** [comment]
> 我在官网`https://chat.openai.com/chat`里面输入一段话得到的回复和程序回复到微信的不一样。
> 
> 官网输入回复的更智能？

每次回复都是通过模型计算的，返回的可能不一样。请求API有参数可以调整，参数可能会影响返回结果。详细代码在gtp目录下，可以参照GPT文档来进行调整。这里的机器人实现的提问是一次性的，并没有上下文参照。

**Comment by 869413421** [comment]
> 我在官网`https://chat.openai.com/chat`里面输入一段话得到的回复和程序回复到微信的不一样。
> 
> 官网输入回复的更智能？

官方的有上下文参照，会更智能，这个项目暂时达不到官方的效果。

**Comment by putianhui** [comment]
> > 我在官`https://chat.openai.com/chat`网上输入一段话得到的回复和程序回复到微信的不一样。
> > 官网输入回复的更多智能？
> 
> 官方的有上下文参考，会更聪明，这个项目暂时达不到官方的效果。

好勒 我明白了  谢谢你
