### ISSUE TITLE
decode config err: invalid character '\n' in string literal

### ISSUE THREAD

**Issue by Gensiss** [869413421/wechatbot#8]
总是自动退出
decode config err: invalid character '\n' in string literal
![image](https://user-images.githubusercontent.com/16629478/206349502-5c1e2456-9434-4c57-aa66-4c7ca51d37fa.png)

**Comment by 869413421** [comment]
> 

配置文件的json有问题，检查一下config.json

**Comment by 869413421** [comment]
> 总是自动退出 decode config err: invalid character '\n' in string literal ![image](https://user-images.githubusercontent.com/16629478/206349502-5c1e2456-9434-4c57-aa66-4c7ca51d37fa.png)

配置文件的json有问题，检查一下config.json
