### ISSUE TITLE
好像并不能继续完成上次的问题

### ISSUE THREAD

**Issue by yn668** [869413421/wechatbot#9]
比如让他些篇作文，他写了，你在让他加点细节，然后又是重新的问题了好像，这个是官方有限制吗

**Comment by yn668** [comment]
行，刚提就更新了，牛

**Comment by 869413421** [comment]
> 行，刚提就更新了，牛

今天刚好增加了上下文功能，更加接近官方效果了

**Comment by yn668** [comment]
> 
但是怎么退出这个问题，不然你重新提问一直在上一个问题的基础上

**Comment by yn668** [comment]
> > 行，刚提就更新了，牛
> 
> 今天刚好增加了上下文功能，更接近官方效果了


> > > 
> > 
> > 
> > 但是怎么退出这个问题，不是你重新提出问题一直在上一个问题的基础上
> 
> 默认会话超时是五分钟，暂停时没有主动态会话的功能。官网也是点按键清空

那这样就有点影响使用，比如你第一个问题问了，基本上5分钟就问不了问题了，他会在前面的问题基础上答非所问，你可以试试

**Comment by yn668** [comment]
> 确实会影反响经验，思考增加主动态清空会议的策略。你有什么好的建议吗

刚才的方案第一种是默认新问题，后来新增了连续对话
能不能加一个判断条件，比如默认是新问题，只有微信选择在上一个问题引用回复时，使用连续对话，就行群聊@回复一样，或者加其他判断的前缀，
也可以默认为引用连续回复，只有加上前缀新：  新+   new： 等关键字，就进行重新对话

**Comment by 869413421** [comment]
解决方案为：
1.将会话超时时间更改为可配置
2.发送固定文本可清空会话上下文

**Comment by f1ndm1** [comment]
> 这个方案可行
